import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import CheckmarkIcon from "../components/Icons/CheckmarkIcon";
import banner from '../img/banner.png'

import Filters from "../components/Filters";
import Subjects from "../components/Subjects";
import Tutors from "../components/Tutors";
import Demands from "../components/Demands";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-96 w-full bg-cover bg-hero-image justify-center items-center">
        <div>
          <h1 className="text-4xl mb-2 text-center text-white">
            Your best tutors, at your home
          </h1>

          <p className="text-center mb-10 text-gray-300">
            Find the right tutor for your children
          </p>

          <Filters />
        </div>
      </div>

      <div>
        <Subjects></Subjects>
      </div>

      <div className="bg-gray-100">
        <Tutors></Tutors>
      </div>

      <div className="">
        <Demands></Demands>
      </div>

      <div className="bg-blue-100">
        <div className="py-6 mx-40">
          <div>
            <h1 className="mb-6 text-2xl font-bold">Find the right tutor for all levels</h1>
            <div className="flex justify-between place-items-center">
              <div className="w-full gap-8">
                <div className="mb-6">
                  <div className="flex gap-2 mb-2">
                    <CheckmarkIcon />
                    <p className="font-bold text-base">Access to many talented tutors nationwide</p>
                  </div>
                  <p className="text-sm font-normal text-gray-700">Find the right tutor that suits you most, for the best cost.</p>
                </div>

                <div className="mb-6">
                  <div className="flex gap-2 mb-2">
                    <CheckmarkIcon />
                    <p className="font-bold text-base">Free 1 day trial</p>
                  </div>
                  <p className="text-sm font-normal text-gray-700">Trial class for one day before paying the tutor fee.</p>
                </div>

                <div className="mb-6">
                  <div className="flex gap-2 mb-2">
                    <CheckmarkIcon />
                    <p className="font-bold text-base">Protected payments</p>
                  </div>
                  <p className="text-sm font-normal text-gray-700">Always know what you'll pay upfront, no costs incurred.</p>
                </div>

                <div className="mb-6">
                  <div className="flex gap-2 mb-2">
                    <CheckmarkIcon />
                    <p className="font-bold text-base">Customer support 24/7</p>
                  </div>
                  <p className="text-sm font-normal text-gray-700">Contact our support team if you have any concerns.</p>
                </div>
              </div>
              <div className="flex justify-end w-full"><Image className="w-max" src={banner} /></div>
            </div>

          </div>
        </div>
      </div>



      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
