import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import CheckmarkIcon from "../components/Icons/CheckmarkIcon";
import banner from "../img/banner.png";

import Filters from "../components/Filters";
import Subjects from "../components/Subjects";
import Tutors from "../components/Tutors";
import Demands from "../components/Demands";
import axios from "axios";
import { CLIENT_DOMAIN } from "@lib/clientConstants";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();

  const logoutHandler = async () => {
    const fetchPromise = await axios.post(
      `${CLIENT_DOMAIN}/api/logout`,
      {},
      {
        withCredentials: true,
      }
    );

    if (fetchPromise.status == 200) {
      // Successfully logged out
      router.push("/login");
    } else {
      // Failed to log out
    }
  };

  return (
    <div>
      <button onClick={logoutHandler}>Logout</button>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/static/favicon.ico" />
      </Head>

      <div className="flex h-96 w-full items-center justify-center bg-hero-image bg-cover">
        <div>
          <h1 className="mb-2 text-center text-4xl text-white">
            Your best tutors, at your home
          </h1>

          <p className="mb-10 text-center text-gray-300">
            Find the right tutor for your children
          </p>

          <Filters />
        </div>
      </div>

      <div>
        <Subjects></Subjects>
      </div>

      <div className="bg-gray-100">
        <Tutors></Tutors>
      </div>

      <div className="">
        <Demands></Demands>
      </div>

      <div className="bg-blue-100">
        <div className="mx-40 py-6">
          <div>
            <h1 className="mb-6 text-2xl font-bold">
              Find the right tutor for all levels
            </h1>
            <div className="flex place-items-center justify-between">
              <div className="w-full gap-8">
                <div className="mb-6">
                  <div className="mb-2 flex gap-2">
                    <CheckmarkIcon />
                    <p className="text-base font-bold">
                      Access to many talented tutors nationwide
                    </p>
                  </div>
                  <p className="text-sm font-normal text-gray-700">
                    Find the right tutor that suits you most, for the best cost.
                  </p>
                </div>

                <div className="mb-6">
                  <div className="mb-2 flex gap-2">
                    <CheckmarkIcon />
                    <p className="text-base font-bold">Free 1 day trial</p>
                  </div>
                  <p className="text-sm font-normal text-gray-700">
                    Trial class for one day before paying the tutor fee.
                  </p>
                </div>

                <div className="mb-6">
                  <div className="mb-2 flex gap-2">
                    <CheckmarkIcon />
                    <p className="text-base font-bold">Protected payments</p>
                  </div>
                  <p className="text-sm font-normal text-gray-700">
                    Always know what you&apos;ll pay upfront, no costs incurred.
                  </p>
                </div>

                <div className="mb-6">
                  <div className="mb-2 flex gap-2">
                    <CheckmarkIcon />
                    <p className="text-base font-bold">Customer support 24/7</p>
                  </div>
                  <p className="text-sm font-normal text-gray-700">
                    Contact our support team if you have any concerns.
                  </p>
                </div>
              </div>
              <div className="flex w-full justify-end">
                <Image className="w-max" src={banner} alt="banner" />
              </div>
            </div>
          </div>
        </div>
      </div>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image
              src="/static/vercel.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
